#!/bin/bash

if [[ `uname` == "Linux" ]]; then
  platform='linux'
elif [[ `uname` == "Darwin" ]]; then
  platform='osx'
fi

ln -s $PWD/.gitconfig $HOME/.gitconfig
ln -s $PWD/.tmux.conf $HOME/.tmux.conf
ln -s $PWD/.vimrc $HOME/.vimrc
ln -s $PWD/.zshrc $HOME/.zshrc
git clone git@github.com:johnswanson/oh-my-zsh $HOME/.oh-my-zsh
mkdir $HOME/{build,bin}

if [[ $platform == "linux" ]]; then
  ln -s $PWD/.xinitrc $HOME/.xinitrc
  ln -s $PWD/.xmobarrc $HOME/.xmobarrc
  mkdir $HOME/.xmonad
  ln -s $PWD/xmonad.hs $HOME/.xmonad/xmonad.hs
fi
