#!/bin/bash

if [[ `uname` == "Linux" ]]; then
  platform='linux'
elif [[ `uname` == "Darwin" ]]; then
  platform='osx'
fi

ln -fs $PWD/.gitconfig $HOME/.gitconfig
ln -fs $PWD/.tmux.conf $HOME/.tmux.conf
ln -fs $PWD/.vimrc $HOME/.vimrc
ln -fs $PWD/.zshrc $HOME/.zshrc

git clone git@github.com:johnswanson/oh-my-zsh $HOME/.oh-my-zsh

cd $HOME/.oh-my-zsh

git remote add upstream git@github.com:robbyrussell/oh-my-zsh

git pull --rebase upstream master

mkdir -p $HOME/{build,bin}

if [[ $platform == "linux" ]]; then
  ln -fs $PWD/.xinitrc $HOME/.xinitrc
  ln -fs $PWD/.xmobarrc $HOME/.xmobarrc
  mkdir -p $HOME/.xmonad
  ln -fs $PWD/xmonad.hs $HOME/.xmonad/xmonad.hs
  mkdir -p $HOME/.config/cower
  ln -fs $PWD/cower_config $HOME/.config/cower/config
fi
