#!/bin/bash

if [[ `uname` == "Linux" ]]; then
  platform='linux'
elif [[ `uname` == "Darwin" ]]; then
  platform='osx'
fi

ln -fs $HOME/.dotfiles/.gitconfig $HOME/.gitconfig
ln -fs $HOME/.dotfiles/.tmux.conf $HOME/.tmux.conf
ln -fs $HOME/.dotfiles/.vimrc $HOME/.vimrc
ln -fs $HOME/.dotfiles/.zshrc $HOME/.zshrc

git clone git@github.com:johnswanson/oh-my-zsh $HOME/.oh-my-zsh

cd $HOME/.oh-my-zsh

git remote add upstream git@github.com:robbyrussell/oh-my-zsh

git pull --rebase upstream master

mkdir -p $HOME/{build,bin}

if [[ $platform == "linux" ]]; then
  ln -fs $HOME/.dotfiles/.xinitrc $HOME/.xinitrc
  ln -fs $HOME/.dotfiles/.xmobarrc $HOME/.xmobarrc
  mkdir -p $HOME/.xmonad
  ln -fs $HOME/.dotfiles/xmonad.hs $HOME/.xmonad/xmonad.hs
  mkdir -p $HOME/.config/cower
  ln -fs $HOME/.dotfiles/cower_config $HOME/.config/cower/config
  ln -fs $HOME/.dotfiles/.Xdefaults $HOME/.Xdefaults
fi
